### ISSUE TITLE
Error parsing an Entangle Power

### ISSUE THREAD

**Issue by Bluesguy1984** [Brennall/tts-hero-mod#6]
**Describe the bug**
I exported this [character ](https://drive.google.com/open?id=1aDRdLcgte7XevlMpOVhQ5W2CnkM4Y_ud])using the latest Json exported and when I tested the [Json file](https://drive.google.com/open?id=1ojzUueFL2II8qz-G4lgrtA6iDyI_wJ9C) with JsonLint.com, I got the following error:

Error: Parse error on line 3974:
...d": 0,			"dice": 3 d6,			3 PD / 3 ED(s
----------------------^
Expecting 'EOF', '}', ',', ']', got 'undefined'

**To Reproduce**
1. Open the HDC file using latest version of Hero Designer
2. Export the character using the latest JSON exporter
3. Take the resulting file and test it using jsonlint.com

**Comment by Brennall** [comment]
Looks like the gap between the "3" and the "d6" is throwing the regex.

**Comment by Brennall** [comment]
![image](https://user-images.githubusercontent.com/1035638/80572928-feeb1200-89f6-11ea-9365-50b80805e626.png)

**Comment by Brennall** [comment]
Cannot access the character. Could you relink please

**Comment by Brennall** [comment]
JSON file shows you are using Standard effect. We are not supporting it at the moment as the whole point of putting the dice rolls on the combat record is to roll dice, not take the standard effect.

![image](https://user-images.githubusercontent.com/1035638/80573338-ab2cf880-89f7-11ea-9ec7-88fd03612996.png)

**Comment by Brennall** [comment]
Closed as no support for Standard Effect.
