### ISSUE TITLE
Problem loading valid Json into the Scene

### ISSUE THREAD

**Issue by Bluesguy1984** [Brennall/tts-hero-mod#8]
**Describe the bug**
Error in Script (Global) function <cbhideGlobal>: chunk_3:(15 10,8-51): attempt to index a nil value
Error in Script (Global) function <scloadChar>: Index was out of range. Must be non-negative and less than the size of the collection. 
Parameter Name: index <4>

**To Reproduce**
1.  Open Notebook
2.  Add New
3.  Enter "Labienus" (no "")
4.  Copy the [Centurion Labienus - JSON.txt](https://github.com/Brennall/tts-hero-mod/files/4828292/Centurion.Labienus.-.JSON.txt) into the body of the Notebook
5.  Click Add Character in HSM Scene
6.  Type in Labienus
7.  Click "Load" next to the name
8.  Error messages

**Expected behavior**

**Screenshots**
![HSM-Error](https://user-images.githubusercontent.com/19332145/85636876-408ae880-b647-11ea-8abb-5b984de36bf2.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]

**Additional context**

**Comment by Brennall** [comment]
Added weight to Jsonkeyword list.

Issue resolved
